[package]
name = "lis"
version = "0.0.10"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
humansize = "2.1"
uzers = "0.12"
git2 = "0.19"
ignore = "0.4"
lscolors = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
csv = "1.3"
terminal_size = "0.4"
unicode-width = "0.2"
colored = "2.1"
nix = { version = "0.29", features = ["fs", "user"] }

[[bin]]
name = "lis"
path = "cli/main.rs"
