name: publish
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  setup:
    runs-on: ubuntu-latest
    # runs only the branch name starts with 'release/v' and the pull request is merged.
    if: startsWith(github.head_ref, 'releases/v') && github.event.pull_request.merged == true
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      appname: ${{ steps.vars.outputs.appname }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Git Tag name
        id: vars
        run: |
          # 後から参照するために、タグ名とアプリケーション名を出力しておく。
          # タグ名は、ブランチ名から 'releases/v' を取り除いたもの。
          # アプリケーション名は、リポジトリ名からオーナー名を取り除いたもの。
          # $GITHUB_OUTPUT に出力することで、後続のジョブから参照できるようになる。
          echo "tag=${GITHUB_HEAD_REF##*/v}" >> $GITHUB_OUTPUT
          echo "appname=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Set git identity
        run: |
          # git tag を push するので、git のユーザ名とメールアドレスを設定しておく。
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Push tag
        run: |
          # タグを作成して、リモートに push する。
          git tag v${{ steps.vars.outputs.tag }}
          git push origin v${{ steps.vars.outputs.tag }}

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # gh コマンドを使って、リリースを作成する。
          # draft として作成する。後続のジョブで、ドラフトを false にする。
          gh release create v${{ steps.vars.outputs.tag }} --verify-tag --generate-notes --title "Release v${{ steps.vars.outputs.tag }}" --draft

  publish:
    runs-on: ${{ matrix.os }}
    needs: setup
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            architecture: arm64
            os_name: linux
            artifact_name: ${{ needs.setup.outputs.appname }}
            ext: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            architecture: amd64
            os_name: linux
            artifact_name: ${{ needs.setup.outputs.appname }}
            ext: ''
          - os: macos-latest
            target: aarch64-apple-darwin
            architecture: arm64
            os_name: darwin
            artifact_name: ${{ needs.setup.outputs.appname }}
            ext: ''
          - os: macos-latest
            architecture: amd64
            os_name: darwin
            target: x86_64-apple-darwin
            artifact_name: ${{ needs.setup.outputs.appname }}
            ext: ''
    outputs:
      tag: ${{ needs.setup.outputs.tag }}
    steps:
      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: build
        run: |
          rustup update stable
          rustup target add ${{ matrix.target }}
          cargo install cargo-zigbuild
          # zigbuild を使って、クロスコンパイルする。
          cargo zigbuild --release --target ${{ matrix.target }}

      - name: Create distribution files.
        run: |
          # 配布用のファイルを作成する。
          ASSET_NAME=${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag}}_${{ matrix.architecture }}_${{ matrix.os_name }}
          mkdir -p dist/$ASSET_NAME
          cp target/${{ matrix.target }}/release/${{ needs.setup.outputs.appname }}${{ matrix.ext }} dist/$ASSET_NAME/
          cp README.md LICENSE dist/$ASSET_NAME/
          tar cvfz dist/${ASSET_NAME}.tar.gz -C dist $ASSET_NAME

      - name: Upload assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # gh コマンドを使って、リリースにアセットをアップロードする。
          ASSET_NAME=${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag}}_${{ matrix.architecture }}_${{ matrix.os_name }}
          gh release upload v${{ needs.setup.outputs.tag }} dist/${ASSET_NAME}.tar.gz

  finalize:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    needs: publish # publish ジョブが完了した後に実行される。
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Finalize release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # gh コマンドを使って、ドラフトを false にする（release が immutable であれば、これ以降変更できない）。
          gh release edit v${{ needs.publish.outputs.tag }} --draft=false
